### ISSUE TITLE
English translation

### ISSUE THREAD

**Issue by antarktikali** [THLfi/koronavilkku-android#10]
What is the schedule for the English translation? Would you accept a pull request for a translated strings.xml file?

**Comment by samikki** [comment]
It is in the schedule and will be available in the near future.

Translation files are of course welcome, but please note that all translations need to go through language and healthcare expert checks. Also, for english, we already have a standing order with the translation agency. 

Sami K / Solita

**Comment by antarktikali** [comment]
Alright, thanks! We'll keep waiting in that case :)

**Comment by albron** [comment]
Why is this issue closed, without the translation?
Keep it open until it's done, please.
