### ISSUE TITLE
Corrections to the Swedish-language UI strings

### ISSUE THREAD

**Issue by sevokn** [THLfi/koronavilkku-android#11]
Corrections to the Swedish-language UI strings in the file app/src/main/res/values-sv/strings.xml .

`<string name="accept_terms_button_enable">Börja använd</string>`
should be
`<string name="accept_terms_button_enable">Börja använda</string>`

`<string name="accept_terms_voluntary_title">Appen är inte oblikatorisk</string>`
should be
`<string name="accept_terms_voluntary_title">Appen är inte obligatorisk</string>`

`<string name="code_entry_en_disabled">Meddelanden om exponering är inte på Gå tillbaka till hem-vyn där du kan koppla på dem</string>`
should be
`<string name="code_entry_en_disabled">Meddelanden om exponering är inte på. Gå tillbaka till hem-vyn där du kan koppla på dem.</string>`

**Comment by hugovk** [comment]
Please see PR #12.

**Comment by solita-jussihei** [comment]
Thanks for the corrections, fixed in latest 1.1.0 update
