### ISSUE TITLE
Improving home screen design

### ISSUE THREAD

**Issue by Rikujolla** [THLfi/koronavilkku-android#14]
As a default the majority of home screen is covered with a big logo telling the app is in use. I think that is a trivial info when you have installed the app. By reducing the size of that information, more essential information could be seen with one glance.
I understand the size when the app is not functioning properly.
EDIT1: The problem seems to be with lower screen resolution. E.g. old Nokia 3 suffers that, the newer Nokia 4.2 is showing all the information without swiping up.
EDIT2: Nokia 3 screenshot:
![Nokia3](https://user-images.githubusercontent.com/10552223/91757154-91cecf80-ebd6-11ea-96a6-dfef6d4e8c78.jpeg)

**Comment by solita-jussihei** [comment]
The app has been shutdown, so closing the issue. Thanks for the suggestion!
