### ISSUE TITLE
Unable to activate app: Altistuslokin käynnistys epäonnistui, tapahtui odottamaton virhe, koodi 17

### ISSUE THREAD

**Issue by subterfugium** [THLfi/koronavilkku-android#15]
Running Oneplus 5T and Microg for LineageOS, Android 9, 2020-08-16.
![Screenshot_20200831-173451_Koronavilkku](https://user-images.githubusercontent.com/4238921/91733064-c2504280-ebb1-11ea-9766-f4ea379993a0.png)

Issue happens when clicking "aloita käyttö".

Please, advise.

**Comment by solita-jussihei** [comment]
Hi, thanks for reporting. The app requires Google Play Services version 20.18.13 or above, and you can verify this version from  device settings, apps, Google Play services and update if necessary. Also there should be a Covid-19 section in device settings if you have a supported version of Google Play services.
https://support.google.com/android/answer/9888358?hl=en

**Comment by subterfugium** [comment]
Thanks for the fast reply. I don't use Google Play Services (it's not installed on my phone), only open-source alternative microg. I installed Koronavilkku by downloading .apk, not via Google Play Store (I don't have one). I believe users with Huawei phones without Google Play Services (sold in Finland) will also suffer from this Google Play Services dependency. Please, consider providing Google Play Service free contact tracing app option, for example, via f-droid.

**Comment by juiceme** [comment]
Hi,

This same error happens even when Google Play services is version 21.6.13-21 [0] [PR327913455]
The device is Google Pixel XL, and android version is 10, service level QP1A.191005.007.A3 dated 2020-07-01

**Comment by hulkkii** [comment]
Before implementing a totally Google Play service free version, I think the first priority should be to enable this for new Huawei phones without Google services (top 3 manufacturer in Finland) by using their alternative to Google's exposure notifications: Huawei Contact Shield API.

**Comment by samikki** [comment]
We are in talks with Huawei about the implementation against Huawei Contact Shield. More information about this in September.

**Comment by paapoh** [comment]
Same problem with Oneplus 7 Pro (10.0.7)
Google Play services 20.30.19.

Covid-19 notifications not turning on in google settings even after installing the app

**Comment by samikki** [comment]
Hello!
The usual cause for this is that the phone does not contain required
Exposure Notification API. It is installed via Google Play and requires
Android 6 or newer. Newest Huaweis that suffer from U.S. boycott also do
not contain Google Play and therefore are not able to use Koronavilkku at
the moment.

Sami

**Comment by paapoh** [comment]
I got Koronavilkku and covid-19 exposure notifications working after I deleted Google Play Services and installed them again

**Comment by juiceme** [comment]
I get the idea that there could be some problems to 3rd party phones but what could be the problem with a *google* Pixel with all recent updates installed?

**Comment by paapoh** [comment]
> I get the idea that there could be some problems to 3rd party phones but what could be the problem with a *google* Pixel with all recent updates installed?

Can you try the same as I did. Go to apps and select Google Play Services. Then open Google Play store window by pressing "App Details" and then uninstall and reinstall it back on.

**Comment by juiceme** [comment]
> > I get the idea that there could be some problems to 3rd party phones but what could be the problem with a _google_ Pixel with all recent updates installed?
> 
> Can you try the same as I did. Go to apps and select Google Play Services. Then open Google Play store window by pressing "App Details" and then uninstall and reinstall it back on.

Seems it is not as easily said as done. The uninstall icon is grayed out and not possible to uninstall. I suppose so many things in the device depend on google services it won't let it be uninstalled.

**Comment by solita-jussihei** [comment]
@juiceme that is a strange problem.. would you be able to capture adb logs while reproducing the error prompt with "koodi 17"? You can filter it for only exposure notification module: 
adb logcat ExposureNotification:D '*:S'

**Comment by OgeonX** [comment]
Huawei here. Please fix.

**Comment by juiceme** [comment]
@solita-jussihei unfortunately the device is not mine, so it is difficult for me to take any debug logs. If it proves possible to do so, I'll do that and post them here.

**Comment by katajanmarja** [comment]
This is not just a Google Services version issue. I suspect it has to do with user containers in Android.

Obseved this error both on Huawei Honor 7 (STF-L09), software version number 9.1.0.201 (Android 9), and on OnePlus A3003, Android version also 9. Google Services version is high enough. Installing the application is not the problem, it's 'Aloita käyttö' that breaks. 

What the two installations have in common is that the primary user of the phone is NOT the user where Koronavilkku is installed. It's installed on a secondary user on the same phone. 

- On secondary user: Get error 17, cannot initialize application ('aloita käyttö').
- Switch to primary user on both phones and install there (without removing the package, no reset efforts): Initialization just works.
- Switch back to secondary user, start app and try to initialize: same error 17.
- Switch to a third user, install app and try to initialize: same error 17.

Please fix this, as the primary user is not the one active when the phone is being actually used, and the app is useless if it only works on one specialized user of the phone.

**Comment by solita-jussihei** [comment]
Thanks @katajanmarja that is a good find! I've reproduced and will try to get more information from Google regarding secondary users. The error 17 generally means that the Exposure Notification module of Google Play Services is not available on the device, and we are working to show more detailed errors in this case.

**Comment by nmurtola** [comment]
Sent the secondary user issue to Google, since it's beyond our control.

**Comment by nmurtola** [comment]
Google responded saying that EN is only supported for the primary profile for now, mainly because of the privacy issues related to various different types of enterprise accounts, e.g. whether it should be possible for an enterprise to push out an app and "force" turn on EN. So as for now users will need to install the app on their personal accounts/devices.
