### ISSUE TITLE
Traceability of the source code

### ISSUE THREAD

**Issue by mikahe** [THLfi/koronavilkku-android#17]
It's mildly troubling that there's no unambiguos mapping between app version in store (phone) and public git repo. Current version is showing "1.0.0.174" and ".174" is possibly some non-public build number.
Currently there are two tags in repo, "v1.0.0-rc.2" and "v1.0.0-rc.1".

I would suggest at least adding tagging of the published (Play Store) versions (including the build number),
and git commit id next to it in the settings version number, e.g. "1.0.0.174  ga91dfa1", in case there actually is connection between the public source code and the installed binary package.

**Comment by ezzkoram** [comment]
Thank you for the comment! We'll add the git commit id to the version string. We use the semver.org specification so the build metadata will be addad after a plus sign e.g. "1.0.1+abcdef0" or "1.0.1-rc.1+abcdef0".

**Comment by ezzkoram** [comment]
Build metadata visible in Google Play Store with newest version 1.0.1+aba6841
