### ISSUE TITLE
Enabling user-selection of text

### ISSUE THREAD

**Issue by fpapado** [THLfi/koronavilkku-android#18]
Hi! I am not certain how user-selection works on native Android apps, so this might be off the mark.
(It could also be that I am missing something. Feel free to close this if it does not apply :) )

Because of a lack of English translations, I am reading the Finnish text. I can understand some of it, but would like to copy-paste it into Google Translate, to make sure that I am not missing anything important.
However, it is not possible to select the text by long-pressing and dragging on the text.

I can also imagine people wanting to copy the text for searching, or sharing with acquaintances.
Currently the solution would be to type back and forth, switching windows, which can range form painful to impossible.

Is it possible to enable user-selection of text?

**Comment by solita-jussihei** [comment]
Hi, unfortunately text selection is not available by default on the text UI element, but we are working on an English translation! The only thing I can suggest is to take a screenshot, open it in Google Photos, and click Google Lens icon on bottom part of screen. This will detect text in the image and allow copy paste.
