### ISSUE TITLE
Marketing cookies against privacy statement

### ISSUE THREAD

**Issue by Rikujolla** [THLfi/koronavilkku-android#21]
When installing the app you must accept the application terms of use. The link directs to the page where as a default e.g. marketing cookies are allowed. That is against the app statements "Your privacy is protected" or "Koronavilkku protects your data and privacy in many ways." I suggest to include Application terms of use internally to the app or care that THL web pages preserve your privacy with default no marketing cookies.

**Comment by nmurtola** [comment]
THL has been informed about this issue.
