### ISSUE TITLE
Clarify licensing for contributions

### ISSUE THREAD

**Issue by htanskanen** [THLfi/koronavilkku-android#22]
This is an issue related to outside contributions to the app and the different licenses applied by THL. There is an identical issue with the iOS app. This issue should be resolved before any outside contributions are incorporated into the app and redistributed under the THL [Terms of Use](https://koronavilkku.fi/kayttoehdot/) via the Play Store.

Currently, the license applicable to the GitHub code base is clearly meant to be [EUPL-1.2](https://spdx.org/licenses/EUPL-1.2.html) which is, outside of EU (state) public sector projects, a rare copyleft-style license. However, the [Terms of Use](https://koronavilkku.fi/kayttoehdot/) for the application as available from the Play Store include licensing conditions of their own. The Terms of Use are not mutually compatible with EUPL-1.2 [*] but are probably necessary and suitable for the official binary app distribution. From the viewpoint of the main copyright holder of the application (THL) this incompatibility would not be an issue as such, since the rights holder has the right to license their own code under different licenses in different contexts, i.e., it's fine to release the sources under EUPL and the Play Store binary under other terms.

However, a problem arises when outside contributions [**] are received through this repository and are incorporated into the application released through the Play Store. Then, from a legal point of view:
* If not specified by the contributor, it is not completely clear what license the code is intended to be contributed under (the so-called "__inbound license__") to the repository. A fair assumption is that the only license given by the contributor to their contribution is the repository main license (EUPL-1.2).
* If the inbound license is EUPL-1.2, and there is nothing further agreed with the contributor about other licenses available to THL for redistribution ("__outbound license__"), then because of the copyleft terms of EUPL-1.2, THL has received no right to relicense and redistribute the contributed code under licenses other than EUPL-1.2 and certain other copyleft-style open source licenses compatible with it. This means __THL has no right to relicense and redistribute the contributed code under their own Terms of Use__ without infringing the EUPL-1.2 license applied to the contribution.

One often-used tool for this is some sort of Contributor License Agreement (CLA) under which contributions are taken in (i.e. an inbound license separate from outbound licensing). The CLA is used to specify under which license(s) the contribution may be redistributed by THL. In this situation, a CLA could be used to enable THL to redistribute (the binary form of) the contributed code in their discretion also under their own Terms of Use. For an example, look at the [CONTRIBUTING file](https://github.com/google/exposure-notifications-android/blob/master/CONTRIBUTING.md) of Google's reference implementation.

A mandatory CLA or copyright assignment to THL is not the only solution. One other option preserving THL's intentions would be to change the GitHub main license from EUPL-1.2 to a more permissive one: e.g. [Apache-2.0](https://spdx.org/licenses/Apache-2.0.html) is widely favored by individuals and corporations as a well-drafted permissive license, but also e.g. MIT is fine, as are different BSD flavors. Subject to not much more than notice obligations, Apache-2.0 or other permissive licenses allow code under them to be easily incorporated into a commercial or otherwise more restrictively licensed application, such as in this case the Play Store binary. This would be a fairly simple and elegant fix. THL would just have to explain in their Open Source Notices (the lack of which is another issue) that the app includes contributions under Apache-2.0 and add the required Apache-2.0 license text in the notices.
 
[*] E.g. under EUPL, the derivative work consisting of the original code and the contribution would have to be redistributed under EUPL-1.2 (or one of the defined compatible other copyleft licenses), and the redistributor "cannot offer or impose any additional terms or conditions on the code that alter or restrict the terms of the [EUPL]". Conflicting terms under the THL Terms of Use are various and include e.g. restrictions on copying or modifying the application as well as on commercial use.

[**] By outside contributions I refer to code contributed to repo by someone other than THL or their subcontractor.

**Comment by PESchmitz** [comment]
The role of copyleft aspects in the EUPL is to protect the original licensor from exclusive (proprietary) appropriations. For licensors that are public bodies, such protection is often seen as an obligation. This is the reason why the EUPL rejects a global re-licensing (in the sense of changing the license) of the covered components by recipients, but accepts that covered code is reused in other source code covered by one of the compatible licenses. You should also consider that EUPL covered components may be linked (even statically) with other software without impacting the other software licensing conditions: according to the European law, the EUPL is not "viral" and inside a project, different components could be licensed differently (some under the EUPL, some under a different licence).  
It is true that the THL terms and conditions seems to be more restrictive than the EUPL, i.e. regarding the prohibition of modifications or regarding the non commercial use (both conditions that are in contradiction with the Open Source Definition), but this is true in comparison with ALL other OSD-compliant licenses and adopting the OSD-compliant Apache license for example would not change anything to the case. As you highlight it, the original licensor THL may apply different conditions. The THL terms of use contain provisions (i.e. regarding personal data protection) that are useful to complement these use conditions, while EUPL terms consider only the rights related to the source code.
Last, if you see any concrete issue, the EUPL community in Joinup has a (free) legal support that will provide further analysis and provide opinion: https://joinup.ec.europa.eu/contact .

**Comment by htanskanen** [comment]
Thank you, @PESchmitz, for the additional background on EUPL. Unfortunately, although switching from EUPL to a more permissive open source license in this app source code repository is _one way_ to address the issue, whether or not EUPL in particular is used is not the core issue here. In short, this issue is about clarifying for all contributors the relationship between the EUPL (which the relevant authority has chosen as the main license of this repository) and the App Terms of Use (unfortunately available currently only in [Finnish here](https://koronavilkku.fi/kayttoehdot/) and I suppose in Swedish, too) which include a _proprietary-style_ license for the app when it is distributed in the Play Store as the official Corona exposure notification app in Finland by the same authority (THL). Solving this issue here does not necessarily require abandoning EUPL. Neither is the issue particular to EUPL. We would have the same issue probably with any copyleft-type license if the current Terms of Use are used as they now are. The exact scope of EUPL's copyleft effect is most likely also irrelevant: contributions to this repository can be made to any parts of the code base, not just as separate components (or "works" in the copyright lingo).

**I want to reiterate that getting rid of EUPL is not the only answer.** However, if you want to maintain EUPL as the main license, but at the same time hold on to the additional restrictions set by the THL Terms of Use for the app store distribution, we should make sure each contributor acknowledges and accepts this (by way of CLAs or perhaps more simply as a clarification/licensing statement prominently included in e.g. the CONTRIBUTING.md file). If this is the way you want to go, we can discuss the best way here.

__Please note that my following discussion with @PESchmitz is slightly off-topic__ and relates only tangentially to this issue to the extent we want to debate whether a copyleft license (such as EUPL) or a permissive-type license should be used for the main open source license in this repository.

> The role of copyleft aspects in the EUPL is to protect the original licensor from exclusive (proprietary) appropriations. For licensors that are public bodies, such protection is often seen as an obligation.

Here, you could half-jokingly say that currently the only "proprietary appropriation" has been done by the authority itself, since they are using two apparently incompatible licenses for the same code, the other one being EUPL, and the other a closed-source license. As far as I know, THL is still the sole right holder for the code base (which is missing any copyright notices, by the way), but issues arise when they start receiving contributions to the source code of the app from the public and distributing them as part of the updated app in the store.

Also, using copyleft licenses, or EUPL specifically, in lieu of permissive open source licenses for public sector code is certainly not seen as an _obligation_ or even a recommendation in Finland. Actually, for comparison, there is an existing _open data_ license [recommendation](http://www.jhs-suositukset.fi/web/guest/jhs/recommendations/189/full) for the public sector pushing for the use of CC BY 4.0, which resembles _permissive_ source code licenses (unlike the copyleft-style BY-SA variants). So, there we have a preference for a permissive, non-copyleft-style license, and there are valid arguments for that approach as well. When a work has been created with public money, you can argue that the result should be released to the public under minimal restrictions, allowing all uses, including commercial ones and also "appropriation" in the sense that commercial players are allowed to remove the work from the "commons" and do business by developing it further as a fully proprietary work.

> ... adopting the OSD-compliant Apache license for example would not change anything to the case. As you highlight it, the original licensor THL may apply different conditions.

It certainly would change things when new licensors (contributors) come into play. In the case of derivative works, for example, Apache-2.0 as the license for the original work does not restrict the licensing choices for the new or modified parts of the work (or existing third-party dependencies), enabling easy integration into closed-source applications. Almost by definition, this is not the case with copyleft-style licenses like EUPL-1.2. In EUPL-1.2, restrictions are created by the copyleft and compatibility clauses under Section 5 which mandate that the whole derivative work must be redistributed under EUPL-1.2 or one of the compatible copyleft licenses listed in the Appendix. Using Apache-2.0 or some other permissive license as the project license, or at least as the license for contributions, would allow THL to safely redistribute the contributed code as part of the application under the current Terms of Use regardless of questions of what is or isn't a derivative work. Conversely, issues may arise if EUPL-licensed outside contributions are intermixed with THL-owned original code and the whole work (application/component) is redistributed under the THL Terms of Use. At worse, this could be an infringement of the contributor's copyright, creating a legal risk for THL and uncertainty in the community as a whole.

**Comment by htanskanen** [comment]
Made a pull request to fix this with an addition to contribution guidelines in CONTRIBUTING.md: https://github.com/THLfi/koronavilkku-android/pull/26 

This would let the project use EUPL-1.2 as the project main license while also letting THL continue to use separate Terms of Use for distribution through the application store.

**Comment by PESchmitz** [comment]
We should avoid that this discussion could lead users into trouble or uncertainty; this hurts my understanding of the role of a lawyer, which is to find solutions and not to invent problems, especially when there are not.
To be clear: nobody wants to maintain EUPL as the main license. This was the choice of THL and I was not involved at all in the process. THL has provided reasons to journalist Gijs Hillenius, who reported it on 27 August in https://joinup.ec.europa.eu/collection/open-source-observatory-osor/news/eupl-copyleft-licence.  This is THL sovereign choice, even if you may prefer Apache or MIT or any other permissive license.
Now the real issue is the apparent conflict (or difference) between the THL “proprietary style” terms and conditions and the “open source” EUPL.
The same kind of issue was met facing article 15 of the DECISION (EU) 2015-2240, stating that: “interoperability solutions established or operated under the ISA2 programme may be used by non-Union initiatives, for non-commercial purposes”. But at the same time and since many years, the Joinup.eu process for publishing and distributing these solutions include the selection of an open source licence that does not differentiate users (Union or non-Union) and does not prohibit commercial use.  So what was the solution? From the licensor point of view it was considered that the objective of the 2015-2240 Decision was to avoid exclusive appropriation by commercial third parties, but that granting a more permissive open licence in specific cases was in conformity with constant EC practice since 2005. From the recipients, users and contributors point of view it is clear that, like in other cases of dual licensing, they can take advantage of the most convenient instrument.

**Comment by htanskanen** [comment]
Agree with @PESchmitz, especially regarding us (outside) lawyers' role. We are enablers and advisors at most, not decision-makers. It seems THL has already opted for releasing the sources under EUPL. My pull request above respects that decision while at the same time addressing other needs expressed by THL, ie. treating distribution of the official app via application stores as a kind of a special case or an exception, leaving THL some room to set and communicate some separate rules for that channel and making sure contributors are also aware of that. 

I hope this is an easy way to remove all possible doubt or confusion regarding the project main license and let the project move on.
