### ISSUE TITLE
Exposure notification system is not enabled until device is rebooted

### ISSUE THREAD

**Issue by kypeli** [THLfi/koronavilkku-android#24]
**Precondition:** 
- OnePlus Nord, latest firmware running Android 10, latest Play Services are installed.
- Bluetooth on, location on
- Koronavilkku installed

**Steps:**
1) Launch Koronavilkku
2) Observe HomeViewFragment

**Expected outcome:**
"Koronavilkku käytössä" is shown

**Actual outcome:**
"Ota Koronavilkku käyttöön" is shown. Koronavilkku is not active.

When pressing the "Ota käyttöön" button, the Exposure Notification system dialog is shown. "Ota käyttöön" is pressed. State in Koronavilkku has not changed, even after relaunching the app. It still says "Ota Koronavilkku käyttöön".

**Solution**:
After rebooting the device, Koronavilkku said "Koronavilkku käytössä".

It's very nice that this issue could be resolved after rebooting the device, but my parents are not supposed to require to reboot the device until Korenavilkku is active, hence I am submitting this as a bug.

**Comment by solita-jussihei** [comment]
Hi @kypeli and thanks for reporting. That is strange and there definitely should not be any need to reboot, and we haven't seen this problem before. It sounds like there is another similar report with the same device #32

**Comment by solita-jussihei** [comment]
Hi @kypeli are you still seeing this issue with latest version?

**Comment by kypeli** [comment]
AFAIK this only happened once and Koronavilkku has worked fine after this initial hiccup and when disabling power management for it.

**Comment by solita-jussihei** [comment]
ok good to hear thanks!
