### ISSUE TITLE
Make it explicit on the website that the app is open source

### ISSUE THREAD

**Issue by haadcode** [THLfi/koronavilkku-android#25]
Hello there,

First, congrats on launching the app and more importantly, massive kudos for open sourcing it (including the backend)! 👏   🎉  Having done that, you've done a great service to the general public and it makes it much easier to trust the application and install it.

However, it took a while for me to learn that this was indeed open source. There's no mention of the fact on the website (and not sure how well this has been communicated to the media, perhaps it's mentioned somewhere) and no links to the Github org/repos. I feel this is absolutely worth higlighting on the website as well as in communications (which I suppose is outside the scope of these repos, but nevertheless). 

It'd be great if the website contained a mention of that as well as links pointing here. Perhaps even add who has audited the app (and how)?

(also, any obstacles to open sourcing the website repo? would be happy to make a PR to add ^ if that existed)

Again, thank you for your work and opening the repos to the public 🙏  ❤️

**Comment by oskar-skog** [comment]
The site even says the opposite of open source:  https://koronavilkku.fi/kayttoehdot/

**Comment by anduck** [comment]
The source code is available here, but is there some way to do a reproducible build which would match binaries served from e.g. Play store? And even if reproducible building is not possible, is any kind of building possible (based on the open source) that would yield a working Koronavilkku app? (I think we don't have access to some configuration parameters that would be needed for that...)

**Comment by solita-jussihei** [comment]
Hi @haadcode thanks for your comments! We've forwarded the suggestion to add info and a link on the website.

@anduck you can build the app with Android Studio/Gradle, but to run it, you need to add local backend configuration in local.properties file (instructions in readme) and you can only run a simDebug build with a simulated Exposure Notifications system since the real live system is restricted by Google for specific app id's.
