### ISSUE TITLE
App says it is not in use and cannot be re-enabled by pressing the button

### ISSUE THREAD

**Issue by manabreak** [THLfi/koronavilkku-android#32]
Almost every time I launch the app, the top portion of the main view says that "Koronavilkku ei ole käytössä" (app is not in use), and there's a button to re-enable it. Pressing this button does nothing.

Bluetooth is enabled on the phone at all times, and it seems that disabling and re-enabling Bluetooth manually fixes the issue.

The device is OnePlus Nord (Oxygen OS 10.5.6.AC01BA).

**Comment by solita-jussihei** [comment]
Hi @manabreak can you test this with latest app version 1.1.0 to see if the problem still occurs?

**Comment by solita-jussihei** [comment]
Hope the issue was resolved, please reopen if not
