### ISSUE TITLE
Provide official apk builds in releases?

### ISSUE THREAD

**Issue by luxas** [THLfi/koronavilkku-android#34]
Hi and thanks for this great application 👌! As a open source enthusiast and professional I'm so proud of being Finnish when seeing this application being open 🙌. Keep up the good work!

**Is your feature request related to a problem? Please describe.**

I have a friend from the US, living in Finland since some time, that cannot download this app because his Google Play region is set to US/North America (or similar). This prevents him from downloading the app through Google Play normally.

This image he sent me illustrates the issue:

![IMG_20200903_192114_741](https://user-images.githubusercontent.com/5442475/92141101-aa2f2c00-ee1a-11ea-841a-8e9dd175d508.jpg)

**Describe the solution you'd like**

I understand that it might not possible to unlock this app for other regions than Finland, but I'd like to consider if you could upload the released apk file (signed if possible) to Github Releases manually or as part of the release machinery.

This would let power users install the app seamlessly from GitHub, without having to rely on sketchy mirrors or reverse engineering.

The same might apply to iOS, but I haven't caught up on how easy/hard it is to install apps manually from packages in recent OS versions.

**Describe alternatives you've considered**

1. Provide instructions on the official site how to install apk:s manually, optionally linking to the latest released apk.
2. Remove the Finnish-region-only restriction (probably impossible)
3. (Current status) Force power users to look for the apk from some unofficial mirror, or have someone else "re-package" the apk from a Finnish phone with the app installed.
4. Declare that it's "impossible" for non-Finnish phones to install the app (because of Play Store policy) in the FAQ of the site.

**Additional context**

See screenshot above.

Thank you for looking into this!

**Comment by luxas** [comment]
Some more info: I have an other friend from Germany which was able to download the Koronavilkku app successfully and start using it, but that required (naturally) that he (temporarily) deactivated the similar German app which previously was active.

This suggests that the download restriction is more region- than country-based.

Additionally, we discussed that to not have to go through the process of manually installing the apk, it might be worth investigating adding the (here proposed) built and published apk to the f-droid repositories as an alternative: https://f-droid.org

**Comment by tatusamma** [comment]
While understandable what kind of a power Apple and Google have here with the whole API, it's a sad day that in the end this whole open source thing is nearly useless in this case.

I was hoping I could build the app myself without having to use google play store and maybe use microg services, but alas, no such luck. If you could even distribute the pure .apk's, that would be a baby step.

**Comment by aaron-r-campbell** [comment]
The app is now available in the US region (source: I downloaded the app from the US region) but having the apk available for direct download and installation would still be a nice way to prevent further region-lock issues.

**Comment by ghost** [comment]
As the application is now globally available and entirely dependent on the Google Play Services, we're not planning to distribute the binaries as direct downloads at this point.
