### ISSUE TITLE
Weekly reminder notification is scary

### ISSUE THREAD

**Issue by kallehjerppe** [THLfi/koronavilkku-android#39]
![notification](https://user-images.githubusercontent.com/2828173/92499707-de349380-f204-11ea-9647-fb7e84a15580.png)

This notification spooked me for a second when it appeared.
Could we remove the "Exposure notifications" text from this?

**Comment by Gonnagle** [comment]
I believe this is actually from Androids Exposure Notification system and thus probably can't be controlled on Koronavilkku App side: https://support.google.com/android/answer/9888358

**Comment by solita-jussihei** [comment]
Yes @Gonnagle you are correct, this notification comes from Google Exposure Notification system. More info here https://support.google.com/android/answer/9991216?hl=en
