### ISSUE TITLE
Home wifi detection

### ISSUE THREAD

**Issue by Frodotus** [THLfi/koronavilkku-android#40]
I'm always frustrated when I need to enable/disable bluetooth scanning when entering/leaving home.
I would like the application to automatically disable device scanning when I am at home and enable it when leaving.
I thought this could be possible by comparing the connected wifi SSID with home wifi name given in application settings.

**Comment by hugovk** [comment]
You could use a third-party app for this, perhaps something like https://play.google.com/store/apps/details?id=it.mf.android.autobluetooth or https://play.google.com/store/apps/details?id=net.dinglisch.android.taskerm

**Comment by Frodotus** [comment]
@hugovk The point is to stop the scanning for nearby devices. Those third-party apps turn bluetooth off. If you turn bluetooth off you can't use another bluetooth devices.

**Comment by denzilferreira** [comment]
@Frodotus 
The WiFi scanning requires additional permissions for the app: ACCESS_FINE_LOCATION, ACCESS_COARSE_LOCATION, CHANGE_WIFI to work across different versions of Android. Adding these permissions to the app would raise significant concerns on people's privacy.

See here, the only permissions required are related to Bluetooth and Internet access:
https://developers.google.com/android/exposure-notifications/implementation-guide

**Comment by solita-jussihei** [comment]
Right @denzilferreira and the app actually cannot request location permissions per the terms of use of Google Exposure Notifications
