### ISSUE TITLE
Take Softagram visual impact reports into use in koronavilkku-android and other repositories

### ISSUE THREAD

**Issue by villelaitila** [THLfi/koronavilkku-android#41]
Hi, I'd like to you you in this project by offering Softagram as (free for open source) a analyzer and code change visualizer to this project integrated in GH PR review workflow. It helps developers to faster get the idea what is the change about and how it matches to the software architecture and the design. Some smells like usage of copy paste code is also reported as part of the Softagram impact report. 

In order to do that, opensource.softagram.com environment can be configured for your three repositories so that the environment is able to get webhook events on PR changes and submit comments into PRs (that contain the report).
The context: https://softagram.com

**Comment by solita-jussihei** [comment]
Thanks for the suggestion, but so far we haven't had a need for PR review tools in this project
