### ISSUE TITLE
Exposure notifications are not available for your device

### ISSUE THREAD

**Issue by MengWoods** [THLfi/koronavilkku-android#68]
I got the error information after clicking the starting using the app.

Exposure notifications could not be turned on
Unfortunately, Google Play Services exposure notifications are not available for your device.
Error code: null

Device: Xiaomi 8

**Comment by solita-jussihei** [comment]
Hi @MorganWoods for some reason Google Play Services fails to use the exposure notification module, but strange that the detailed error is missing.. Could you check and update your Xiaomi system version, and Google play services version? And you've installed the app normally through Play Store?

Also, secondary user profiles won't work, but in that case you should get a specific error message

**Comment by solita-jussihei** [comment]
Assuming you got this resolved, let us know if you still have the problem
