### ISSUE TITLE
View bindings are not set to null in onDestroyView 

### ISSUE THREAD

**Issue by atte-m** [THLfi/koronavilkku-android#7]
Not nulling the bindings could lead to memory leaks as fragment lifecycle is different from fragment's views lifecycle. It is recommended by view binding docs https://developer.android.com/topic/libraries/view-binding#fragments

**Comment by solita-jussihei** [comment]
Thanks for pointing that out! We'll take a look at this for later releases

**Comment by Kaaveh** [comment]
I can fix this if you allow me.

**Comment by houssemzaier** [comment]
later means never @Kaaveh

**Comment by solita-jussihei** [comment]
The app has been shutdown, so closing the issue. Thanks for the suggestion!
