### ISSUE TITLE
Is it only available if Google play account is set to Finland?

### ISSUE THREAD

**Issue by finmackandal** [THLfi/koronavilkku-android#8]
Hi

Goople play says that my device is not compatible, but OS version is higher than required.
My region/country in Google Play account isn't set to Finland.

It seems that is not possible to download the app if the country is not set to Finland.

Considering we would like a massive use of the app I suggest such limitations are removed.

I was hopping this app and now I cannot install it, IMO, less motivated users might discard it if they found with this issue.

**Comment by shnigi** [comment]
I just want to comment that this limitation should be removed in my opinion as well. I am currently in Australia and they have limited their covid safe app onto australian markets only and as I have my store set to Finland there is no way I can cooperate with the local systems as I cant install the app. I believe there might be many people whose store is set to somewhere else.

**Comment by Temetz** [comment]
The distribution limitation might be enforced by Google as they only allow one app per country.

**Comment by kingslef** [comment]
The same issue was raised for Germany's corona app, and eventually it was released for some other countries: https://www.coronawarn.app/en/faq/#international. See also the issue in https://github.com/corona-warn-app/cwa-app-ios/issues/623.

**Comment by solita-jussihei** [comment]
@finmackandal country availability was updated earlier today, right after release, so this update was maybe not active yet.. can you try again?

**Comment by finmackandal** [comment]
I just installed it, so I think it is already solved!
Kiitos!
