### ISSUE TITLE
Add koronavilkku to F-Droid

### ISSUE THREAD

**Issue by stopusingthisplatformplease** [THLfi/koronavilkku-android#9]
Any plans of adding koronavilkku to the free/open source app store [F-Droid](https://f-droid.org/) so Android users who does not have a Google-account can download it?

**Comment by ZeiP** [comment]
As far as I understand, the application is not usable unless Google Play Services are unavailable (as mentioned in #15). If/when that is the case, is publishing to F-Droid useful?

**Comment by murtoM** [comment]
Could it be made to work on devices with no Google Play Services? For example some kind of FOSS build flavour?

**Comment by samikki** [comment]
Sounds interesting. If F-Droid would contain its own implementation of ENS, the situation would be somewhat similar to integrating to Huawei's service. We are of course open to investigate and discuss about this but cannot make any promises at the moment. 

Sami K / Solita

**Comment by murtoM** [comment]
Looks like [microG has added an initial implementation of the API](https://github.com/microg/android_packages_apps_GmsCore/commit/5f70d943cbceabcd9d2c72f8460ea58cba7e08fb). Though still a open source implementation of the client libraries is needed for F-Droid inclusion.

**Comment by tatusamma** [comment]
Yes, pretty please offer some alternative to google play store if possible. I'd even rather build the app myself instead of getting it from the play store.

**Comment by HermannDppes** [comment]
For the German app there is an analogous debate going on: https://github.com/corona-warn-app/cwa-app-android/issues/75

In particular, this project might be relevant: https://github.com/CoraLibre/CoraLibre-android-sdk
